general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# lock after 5 min
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# turn off monitors after 5.5 min (after lock is already rendered)
listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
